#!/bin/bash

###############################################################################
# Firebase Configuration Helper Script
# This script helps you set up Firebase configuration quickly
###############################################################################

echo "🔥 Firebase Configuration Helper"
echo "================================="
echo ""
echo "This script will help you configure Firebase for your application."
echo ""
echo "📋 What you need:"
echo "   1. Access to Firebase Console"
echo "   2. Your Firebase web app configuration"
echo ""
echo "🌐 Step 1: Open Firebase Console"
echo "================================="
echo ""
echo "Please open this URL in your browser:"
echo ""
echo "   https://console.firebase.google.com/project/operty-b54dc/settings/general"
echo ""
read -p "Press ENTER when you have the Firebase Console open..."

echo ""
echo "🔍 Step 2: Find Your Web App Config"
echo "===================================="
echo ""
echo "In the Firebase Console:"
echo "   1. Scroll down to 'Your apps' section"
echo "   2. Look for a Web app (</> icon)"
echo "   3. If no web app exists, click 'Add app' → Web"
echo "   4. Click on your web app"
echo "   5. Look for 'SDK setup and configuration'"
echo "   6. Click 'Config' radio button"
echo ""
echo "You should see something like:"
echo ""
echo "   const firebaseConfig = {"
echo "     apiKey: \"AIzaSy...\","
echo "     authDomain: \"operty-b54dc.firebaseapp.com\","
echo "     projectId: \"operty-b54dc\","
echo "     storageBucket: \"operty-b54dc.firebasestorage.app\","
echo "     messagingSenderId: \"914547669275\","
echo "     appId: \"1:914547669275:web:...\","
echo "     measurementId: \"G-...\""
echo "   };"
echo ""
read -p "Press ENTER when you can see this config..."

echo ""
echo "✏️  Step 3: Enter Your Configuration"
echo "====================================="
echo ""

# Get API Key
echo -n "Enter your Firebase API Key (starts with AIzaSy...): "
read api_key

# Get App ID
echo -n "Enter your Firebase App ID (starts with 1:914547669275:web:...): "
read app_id

# Get Measurement ID (optional)
echo -n "Enter your Measurement ID (starts with G-...) [optional, press ENTER to skip]: "
read measurement_id

# Create .env.local file
cat > .env.local << EOF
# Firebase Configuration
# Auto-generated by setup script on $(date)

NEXT_PUBLIC_FIREBASE_API_KEY=$api_key
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=operty-b54dc.firebaseapp.com
NEXT_PUBLIC_FIREBASE_PROJECT_ID=operty-b54dc
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=operty-b54dc.firebasestorage.app
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=914547669275
NEXT_PUBLIC_FIREBASE_APP_ID=$app_id
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$measurement_id

# Optional: Google Maps
NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=

# Environment
NODE_ENV=development
EOF

echo ""
echo "✅ Configuration saved to .env.local"
echo ""
echo "📄 Generated .env.local file:"
echo "=============================="
cat .env.local
echo "=============================="
echo ""

# Validate
if [[ -z "$api_key" || -z "$app_id" ]]; then
    echo "⚠️  WARNING: Some required fields are empty!"
    echo "   Please edit .env.local and fill in the missing values."
    echo ""
    echo "   File location: $(pwd)/.env.local"
    echo ""
else
    echo "✅ Configuration looks good!"
    echo ""
fi

echo "🚀 Step 4: Restart Your Development Server"
echo "==========================================="
echo ""
echo "To apply the changes:"
echo "   1. Stop the current dev server (Ctrl+C)"
echo "   2. Run: npm run dev"
echo "   3. Check browser console for Firebase initialization messages"
echo ""
echo "You should see:"
echo "   ✅ Firebase initialized successfully (browser)"
echo ""

echo "🎯 Step 5: Create Admin Account"
echo "================================"
echo ""
echo "Once the server is running:"
echo "   1. Go to: http://localhost:3000/auth/signup"
echo "   2. Create an account with email: admin@siamoon.com"
echo "   3. Use the admin-setup page to grant admin privileges"
echo ""

echo "✅ Setup complete! Good luck! 🎉"
echo ""
